name: build

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main ]
    paths:
    - '**/*.cs'
    - '**/*.csproj'

jobs:
  build:

    name: build-${{matrix.os}}-${{matrix.dotnet}}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: src
    strategy:
      matrix:
        os: [ubuntu-latest] #, windows-latest, macOS-latest]
        dotnet: ['8.x'] # Just a single target for now

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal